//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pjHandOverList
    {
        public int pjHandOverId { get; set; }
        public Nullable<int> pjId { get; set; }
        public string pjActionItem { get; set; }
        public string pjAskMemberId { get; set; }
        public string pjReplyEmpId { get; set; }
    
        public virtual pjHandOverList pjHandOverList1 { get; set; }
        public virtual pjHandOverList pjHandOverList2 { get; set; }
    }
}
