//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pjOverall
    {
        public int pjOverallId { get; set; }
        public string pjInput { get; set; }
        public string pjGoal { get; set; }
        public string pj最壞情況評估 { get; set; }
        public string pj是否繼續 { get; set; }
        public Nullable<decimal> pjCost { get; set; }
        public Nullable<decimal> pj收入 { get; set; }
        public Nullable<decimal> pj獲利 { get; set; }
        public string pj審核 { get; set; }
        public string pjMemo { get; set; }
        public Nullable<int> pjId { get; set; }
        public string pjActionItem { get; set; }
    
        public virtual pjProject pjProject { get; set; }
    }
}
