//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pjProject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pjProject()
        {
            this.pjAdvice = new HashSet<pjAdvice>();
            this.pjMeeting = new HashSet<pjMeeting>();
            this.pjOverall = new HashSet<pjOverall>();
            this.pjReport = new HashSet<pjReport>();
            this.pjTeam = new HashSet<pjTeam>();
        }
    
        public int pjId { get; set; }
        public string pjName { get; set; }
        public string pjManager { get; set; }
        public Nullable<decimal> pjBudget { get; set; }
        public string pjIntroduction { get; set; }
        public Nullable<int> pjMemberCount { get; set; }
        public string pjClient { get; set; }
        public string pj初審結果 { get; set; }
        public string pj複審結果 { get; set; }
        public Nullable<System.DateTime> pj開始日期 { get; set; }
        public Nullable<System.DateTime> pj結束日期 { get; set; }
        public string pjManagerId { get; set; }
        public string pj預估時間 { get; set; }
        public string pj審核階段 { get; set; }
        public string pj結案 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pjAdvice> pjAdvice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pjMeeting> pjMeeting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pjOverall> pjOverall { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pjReport> pjReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pjTeam> pjTeam { get; set; }
    }
}
