//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pjTeam
    {
        public int pjTeamId { get; set; }
        public Nullable<int> pjId { get; set; }
        public string pjMemberId { get; set; }
        public string pjMemberName { get; set; }
        public string pjTarget { get; set; }
        public string pjMember部門 { get; set; }
        public string pjPhase { get; set; }
        public string pjDuration { get; set; }
        public string pjTask { get; set; }
        public string pjFixedDuration { get; set; }
        public Nullable<System.DateTime> pjTaskStartDate { get; set; }
        public Nullable<System.DateTime> pjTaskEndDate { get; set; }
    
        public virtual pjProject pjProject { get; set; }
    }
}
