//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pj團隊
    {
        public int pj { get; set; }
        public string pj成員7 { get; set; }
        public string pj工作項目7 { get; set; }
        public Nullable<int> pjId { get; set; }
        public string pj成員6 { get; set; }
        public string pj工作項目6 { get; set; }
        public string pj成員5 { get; set; }
        public string pj工作項目5 { get; set; }
        public string pj成員4 { get; set; }
        public string pj工作項目4 { get; set; }
        public string pj成員3 { get; set; }
        public string pj工作項目3 { get; set; }
        public string pj成員2 { get; set; }
        public string pj工作項目2 { get; set; }
        public string pj成員1 { get; set; }
        public string pj工作項目1 { get; set; }
    }
}
