//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pj建立
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pj建立()
        {
            this.pj總表 = new HashSet<pj總表>();
        }
    
        public string pjCreateId { get; set; }
        public string pj簡介 { get; set; }
        public Nullable<decimal> pjBudget { get; set; }
        public Nullable<int> pj成員數 { get; set; }
        public string pj客戶 { get; set; }
        public string pj審核狀態 { get; set; }
        public string pj初審意見 { get; set; }
        public string pj複審意見 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pj總表> pj總表 { get; set; }
    }
}
