//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pj控管
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pj控管()
        {
            this.pj總表 = new HashSet<pj總表>();
        }
    
        public string pjPlannedAndControl { get; set; }
        public Nullable<System.DateTime> pjStartDate { get; set; }
        public Nullable<System.DateTime> pjEndDate { get; set; }
        public string pjGoal { get; set; }
        public string pjIntput { get; set; }
        public string pjIssueLog { get; set; }
        public string pjAuthorization { get; set; }
        public string pjWorstCaseScenario { get; set; }
        public string pjGoOrNogo { get; set; }
        public Nullable<int> pjScheduleId { get; set; }
    
        public virtual pj進度表 pj進度表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pj總表> pj總表 { get; set; }
    }
}
