//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pj結案
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pj結案()
        {
            this.pj總表 = new HashSet<pj總表>();
        }
    
        public string pjFinalReport { get; set; }
        public string pjFinalManager { get; set; }
        public Nullable<int> pjFinalDuration { get; set; }
        public Nullable<int> pjFinal成員數 { get; set; }
        public string pjFinal客戶 { get; set; }
        public string pjDone { get; set; }
        public Nullable<decimal> pjEarn { get; set; }
        public Nullable<decimal> pjFinalCost { get; set; }
        public string pjFinal簽核 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pj總表> pj總表 { get; set; }
    }
}
