//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pj進度表
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pj進度表()
        {
            this.pj控管 = new HashSet<pj控管>();
        }
    
        public int pjScheduleId { get; set; }
        public Nullable<int> pjMemberId { get; set; }
        public string pjMemberName { get; set; }
        public string pjActionItem { get; set; }
        public string pjPhase { get; set; }
        public Nullable<int> pjDuration { get; set; }
        public string pjTarget { get; set; }
        public Nullable<int> pjFixedDuration { get; set; }
        public Nullable<decimal> pjEstimation { get; set; }
        public string pjLag { get; set; }
        public string pjObjective { get; set; }
        public string pjHandOver { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pj控管> pj控管 { get; set; }
    }
}
